Program
	= { Function
	| Declaration, ";" };

Function
	= Identifier, "(", [ Parameters ], ")", Type, Statement;

Parameters
	= Parameter, { ",", Parameter };

Parameter
	= Identifier, Type;

Statement
	= ( [ SimpleStatement ], ";" )
	| Block
	| IfStatement
	| WhileStatement
	| ForStatement
	| ReturnStatement;

ReturnStatement
	= "return", [ Expression ];

SimpleStatement
	= Declaration
	| Assignment
	| Expression
	| BreakStatement
	| ContinueStatement;

WhileStatement
	= "while", "(", Expression, ")", Statement;

ForStatement
	= "for", "(", Identifier, Type, "in", Expression, ")", Statement;

BreakStatement
	= "break";

ContinueStatement
	= "continue";

IfStatement
	= "if", "(", Expression, ")", Statement, [ "else", Statement ];

Block
	= "{", { Statement }, "}";

Declaration
	= Identifier, Type, [ ":", Expression ];

Type
	= Identifier, [ Template ], [ "?" ];

Template
	= "<", Generics, ">";

Generics
	= Type, { ",", Type };

Assignment
	= Primary, ":", Expression;

Expression
	= Disjunction;

Disjunction
	= Conjunction, { "|", Conjunction };

Conjunction
	= Relation, { "&", Relation };

Relation
	= Additive, { ( "<"
	| ">"
	| "<="
	| ">="
	| "!="
	| "=" ), Additive };

Additive
	= Multiplicative, { ( "+"
	| "-" ), Multiplicative };

Multiplicative
	= Prefix, { ( "*"
	| "/" ), Prefix };

Prefix
	= [ ( "+"
	| "-"
	| "!" ) ], Primary;

Primary
	= Atomic, { Postfix };

Postfix
	= ".", Identifier
	| "(", [ Arguments ], ")"
	| "[", Expression, "]";

Atomic
	= "null"
	| Number
	| Boolean
	| Character
	| String
	| Designator
	| "(", Expression, ")"
	| "[", [ Arguments ], "]";

Designator
	= Identifier, [ Template
	| Invocation ];

Invocation
	= "(", [ Arguments ], ")";

Arguments
	= Expression, { ",", Expression };

Identifier
	= Letter, { Letter
	| Digit };

String
	= '"', { Any - '"' }, '"';

Character
	= "'", Any - "'", "'";

Letter
	= "a"
	| "b"
	| "c"
	| "d"
	| "e"
	| "f"
	| "g"
	| "h"
	| "i"
	| "j"
	| "k"
	| "l"
	| "m"
	| "n"
	| "o"
	| "p"
	| "q"
	| "r"
	| "s"
	| "t"
	| "u"
	| "v"
	| "w"
	| "x"
	| "y"
	| "z"
	| "A"
	| "B"
	| "C"
	| "D"
	| "E"
	| "F"
	| "G"
	| "H"
	| "I"
	| "J"
	| "K"
	| "L"
	| "M"
	| "N"
	| "O"
	| "P"
	| "Q"
	| "R"
	| "S"
	| "T"
	| "U"
	| "V"
	| "W"
	| "X"
	| "Y"
	| "Z"
	| "_";

Boolean
	= "true"
	| "false";

Number
	= Integer, [ ".", Integer ];

Integer
	= Digit, { Digit };

Digit
	= "0"
	| "1"
	| "2"
	| "3"
	| "4"
	| "5"
	| "6"
	| "7"
	| "8"
	| "9";

Any
	= ? any valid source character ?;
